### ISSUE TITLE
Cannot run server under Debian (AppImage and binaries)

### ISSUE THREAD

**Issue by ghost** [lassiterm/AM2R-Server#2]
I'm unable to run this server under Linux.
Here is my configuration : (uname -a)
```
Linux comp.<hidden> 5.4.124-1-pve #1 SMP PVE 5.4.124-1 (Wed, 23 Jun 2021 13:47:09 +0200) x86_64 GNU/Linux
```

I tried with a fresh Debian 10 install, it doesn't work. I get each time a No such file or directory error.

```
root@comp ~ # ./AM2R_Server_1.3.AppImage 
execv error: No such file or directory
```

```
root@comp ~/AM2R_Server # ./runner
-bash: ./runner: No such file or directory
```

I don't have any Windows Server, so I must run the server to play with my friends with my poor connection.

Any idea how to with this ?

**Comment by milesthenerd** [comment]
Sorry, I just now saw this as an open issue. Apparently I'm horrible at checking GitHub notifications.

A couple of questions for the AppImage since the raw binary has a bunch of dependencies:
1. Do you have multilib enabled (probably called i386 arch)?
2. Did you set the file to be executable?

**Comment by ghost** [comment]
No problem !
I tried on a couple servers and my computer.

Multilib was not enabled.
But even after I added it (`sudo dpkg --add-architecture i386`), I had to install the following packages to run the server : `ia32-libs libssl1.0.0:i386`

Thank you for your help

**Comment by milesthenerd** [comment]
Glad you were able to get it working!
